from ifrappy.main_iFRAP import ExperimentGroup
from ifrappy.plot_library import swarmy_boxes, bar_graphs, perform_statistical_test
from ifrappy.granule_proteins import generate_granule_data, generate_glycogenase_data